### ISSUE TITLE
Search Results Design Review

### ISSUE THREAD

**Issue by vincent-young-1701** [benetech/ImageShare#67]
![image](https://user-images.githubusercontent.com/25315048/80505543-502cd000-8929-11ea-81fd-5a54529833f4.png)

- Here using the same search module as the home, and seems just labelling would need to change, such as maybe the “Search Results” submit button or “Search results results” input label, but those can be tailored when the time comes.  I’ve got the “Refine Results” header at the top.  I put in a header background color which also carries over to the detail page so there’s more consistency.  Only thing I felt funny about was the Refine results search module appears before the results....maybe it’s better to put it after?

**Comment by clapierre** [comment]
Issue there would be if there were 10,000 results if they just search a particular subject, we don't want to have them scroll to the bottom in order to refine the search.  So it makes sense to have the Refine search results above the list.

Question thou would be where would the focus go for a SR when they get to this page.  Would it be an issue to put the focus on the "# of Resources Found" and the can move fwd to investigate the resource found and move backwards to refine the search. 

I assume that is not good practice to do that, in which case we should move the # of resources found above the Refine Search, and maybe have a Hidden AT link just after the # of resources found to Jump to the Resources instead of forcing them to move past the refine search section.  Or have a details /summary to open the Refine Search section.

Just trying to figure out the best way so that when you search for "Heart" and you get to the next page of results you get the important information announced "# of resources found" and then you can get to the list of resources very easily instead of having to wade through all the refine search stuff always before you get to the # of resources found and the actual resources themselves.

What do you recommend?

**Comment by vincent-young-1701** [comment]
I think that if we just have the h1 above the refine results h2 heading should fix it, no?

**Comment by vincent-young-1701** [comment]
Check this on oute.  I don't think a visual heading is needed for the search if we are moving the H1 heading to the top.  Thoughts?
 
![Search Results Desktop](https://user-images.githubusercontent.com/25315048/80521411-d6541100-893f-11ea-9550-d7c5cc72b49d.png)

**Comment by sinabahram** [comment]
Just want to state again that pagination is required, but still important to keep in mind because if they have selected showing 100 results at a time, the issue still exists per Charles’ point.

**Comment by vincent-young-1701** [comment]
Sina, good point.  I think a simple pagination centered at the bottom is going to work with standard text, first page, previous page, numbers, next page, and last page.  Also added the current result range displaying "Displaying 12 to 15 of 354 results." under the h1 heading. @clapierre anything else we are missing on this page?  How does that look?
![Search Results Desktop](https://user-images.githubusercontent.com/25315048/80524459-86c41400-8944-11ea-93ca-241470e6e576.png)

**Comment by clapierre** [comment]
Yes, I like this although we will want to specify also how many resources to show at one time, 5, 10, 25, 50, 100
What do you think is there some standard for this, and where would you be able to change that?

**Comment by vincent-young-1701** [comment]
We can put that in the top right corner of the table, just above it as a dropdown.

**Comment by clapierre** [comment]
What about how Bookshare does this with this at the top/bottom?
with a dropdown choice for # per page, and the links to beginning / end and individual pages.

https://www.bookshare.org/search?keyword=Maple

**Comment by vincent-young-1701** [comment]
How does this look?  Keeping it simple is always my initial approach with the "Results per page" dropdown in the top right corner above the table.  If after implementation, we feel both at the top and bottom is needed along with pagination, we can add in?  Thoughts? 

![Search Results Desktop](https://user-images.githubusercontent.com/25315048/80526282-5d58b780-8947-11ea-809e-1bd5da208b5d.png)

**Comment by clapierre** [comment]
I like this, I think it's fine the way you have it.
Thanks!  Looks great.

**Comment by vincent-young-1701** [comment]
Great!

**Comment by sinabahram** [comment]
Charles, concept-wise, yes, but implementation wise, hard no. that’s not very accessible markup I’m sorry to say. It’s technically accessible but we have way better patterns that we use for pagination.

**Comment by sinabahram** [comment]
I agree with the dropdown, and the usual progression is 10, 20, and 50, but we may wish to do 20, 50, and 100, to be honest, as 10 always seems like too few to me.

 

Also, note my previous comment about markup has to do with pagination, not number of results per page. Sorry if any confusion.
